spring:
  datasource:
    url: jdbc:mysql://cdb-a1hhizuq.bj.tencentcdb.com:10118/lemon_as_drug
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: zhangwenjing0501

mybatis:
    configuration:
      map-underscore-to-camel-case: true

server:
  port: 10001