spring:
  datasource:
    url: jdbc:mysql://localhost:3306/ningmeng_user?serverTimezone=GMT%2B8
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: 123456

mybatis:
    configuration:
      map-underscore-to-camel-case: true

server:
  port: 10001